# Generated by Django 6.0.5 on 2026-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='max_classes_per_day',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='max_classes_per_week',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], default='FULL_TIME', max_length=20),
        ),
    ]
