# Generated by Django 6.0.5 on 2026-05-27 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0002_remove_batch_course_batch_courses_course_fee_amount'),
        ('teacher', '0002_teacherprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='institute_admin.course'),
        ),
    ]
