# Generated by Django 6.0.5 on 2026-05-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0003_alter_notice_options_notice_category_and_more'),
        ('student_parent', '0003_studentprofile_current_school_address_and_more'),
        ('teacher', '0004_homeworkattachment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'batch', 'date')},
        ),
    ]
