# Generated by Django 6.0.5 on 2026-05-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0004_academicyear'),
        ('student_parent', '0008_alter_studentenrollment_options_and_more'),
        ('teacher', '0005_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student_parent.studentacademicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('academic_session', 'batch', 'date')},
        ),
    ]
