# Generated by Django 6.0.5 on 2026-05-28 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_parent', '0009_alter_studentenrollment_academic_session'),
        ('teacher', '0006_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student_parent.studentacademicsession'),
        ),
    ]
