# Generated by Django 6.0.5 on 2026-05-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_attendance_academic_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ['exam', 'student__user__first_name', 'student__user__username']},
        ),
    ]
