# Generated by Django 6.0.5 on 2026-06-03 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0007_academicyear_ay_inst_active_idx_and_more'),
        ('student_parent', '0012_guardianprofile_guardian_primary_idx_and_more'),
        ('super_admin', '0002_mobilerefreshtoken'),
        ('teacher', '0008_alter_examresult_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['academic_session', '-date', 'status'], name='att_session_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', '-date'], name='att_student_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['batch', 'date', 'status'], name='att_batch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['batch', '-exam_date'], name='exam_batch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student'], name='exam_result_student_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['batch', 'due_date', '-created_at'], name='hw_batch_due_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['course', 'due_date'], name='hw_course_due_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworkattachment',
            index=models.Index(fields=['homework', '-uploaded_at'], name='hw_attach_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['institute', 'is_active'], name='teacher_inst_active_idx'),
        ),
    ]
