# Generated by Django 6.0.5 on 2026-06-03 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_exam_academic_year(apps, schema_editor):
    Exam = apps.get_model('teacher', 'Exam')
    for exam in Exam.objects.select_related('batch').filter(academic_year__isnull=True):
        if exam.batch_id and exam.batch.academic_year_id:
            exam.academic_year_id = exam.batch.academic_year_id
            exam.save(update_fields=['academic_year'])


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0007_academicyear_ay_inst_active_idx_and_more'),
        ('student_parent', '0012_guardianprofile_guardian_primary_idx_and_more'),
        ('teacher', '0009_attendance_att_session_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('unattempted_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttemptUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exams/rough-work/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['question__order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='exams/questions/')),
                ('marks', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='institute_admin.academicyear'),
        ),
        migrations.RunPython(backfill_exam_academic_year, migrations.RunPython.noop),
        migrations.AddField(
            model_name='exam',
            name='allow_rough_work_uploads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='institute_admin.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_result_after_submit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_year', 'batch', '-exam_date'], name='exam_year_batch_date_idx'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='student_parent.studentacademicsession'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='teacher.exam'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='student_parent.studentprofile'),
        ),
        migrations.AddField(
            model_name='examattemptupload',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='teacher.examattempt'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teacher.exam'),
        ),
        migrations.AddField(
            model_name='examattemptupload',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rough_work_uploads', to='teacher.examquestion'),
        ),
        migrations.AddField(
            model_name='examquestionattempt',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='teacher.examattempt'),
        ),
        migrations.AddField(
            model_name='examquestionattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='teacher.examquestion'),
        ),
        migrations.AddField(
            model_name='examquestionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='teacher.examquestion'),
        ),
        migrations.AddField(
            model_name='examquestionattempt',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_attempts', to='teacher.examquestionoption'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', '-started_at'], name='exam_attempt_student_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'submitted_at'], name='exam_attempt_submit_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('exam', 'academic_session')},
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'order'], name='exam_question_order_idx'),
        ),
        migrations.AddIndex(
            model_name='examattemptupload',
            index=models.Index(fields=['attempt', 'question'], name='exam_upload_attempt_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestionoption',
            index=models.Index(fields=['question', 'order'], name='exam_option_order_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestionattempt',
            index=models.Index(fields=['attempt', 'question'], name='exam_q_attempt_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examquestionattempt',
            unique_together={('attempt', 'question')},
        ),
    ]
