# Generated by Django 6.0.5 on 2026-06-03 13:48

import django.db.models.deletion
from django.db import migrations, models


def backfill_exam_subjects(apps, schema_editor):
    Exam = apps.get_model('teacher', 'Exam')
    Subject = apps.get_model('institute_admin', 'Subject')
    for exam in Exam.objects.select_related('course', 'batch').filter(subject__isnull=True, course__isnull=False):
        course = exam.course
        academic_year_id = exam.academic_year_id or (exam.batch.academic_year_id if exam.batch_id else course.academic_year_id)
        if not academic_year_id:
            continue
        subject, _created = Subject.objects.get_or_create(
            institute_id=course.institute_id,
            academic_year_id=academic_year_id,
            name=course.name,
            defaults={
                'description': course.description,
                'is_active': course.is_active,
            },
        )
        exam.subject_id = subject.pk
        exam.save(update_fields=['subject'])


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0008_subject'),
        ('teacher', '0010_examattempt_examattemptupload_examquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='institute_admin.subject'),
        ),
        migrations.RunPython(backfill_exam_subjects, migrations.RunPython.noop),
    ]
