# Generated by Django 6.0.5 on 2026-06-03 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_exam_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttemptActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='teacher.examattempt')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['attempt', 'event_type'], name='exam_activity_type_idx'), models.Index(fields=['attempt', 'occurred_at'], name='exam_activity_time_idx')],
            },
        ),
    ]
