# Generated by Django 6.0.5 on 2026-06-23 01:33

import super_admin.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_homework_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattemptupload',
            name='image',
            field=models.ImageField(upload_to=super_admin.media_utils.exam_rough_work_upload_path),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='image',
            field=models.ImageField(blank=True, upload_to=super_admin.media_utils.exam_question_image_upload_path),
        ),
        migrations.AlterField(
            model_name='homeworkattachment',
            name='file',
            field=models.FileField(upload_to=super_admin.media_utils.homework_attachment_upload_path),
        ),
    ]
