from django.urls import path

from . import views

app_name = "institute_admin"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("software-tour/", views.software_tour, name="software_tour"),
    path(
        "billing/payments/<int:pk>/bill/",
        views.subscription_payment_bill,
        name="subscription_payment_bill",
    ),
    path("academic-year/switch/", views.academic_year_switch, name="academic_year_switch"),
    path("courses/", views.course_list, name="course_list"),
    path("courses/create/", views.course_create, name="course_create"),
    path("courses/<int:pk>/edit/", views.course_update, name="course_update"),
    path("courses/<int:pk>/delete/", views.course_delete, name="course_delete"),
    path("subjects/", views.subject_list, name="subject_list"),
    path("subjects/create/", views.subject_create, name="subject_create"),
    path("subjects/<int:pk>/edit/", views.subject_update, name="subject_update"),
    path("subjects/<int:pk>/delete/", views.subject_delete, name="subject_delete"),
    path("fee-categories/", views.fee_category_list, name="fee_category_list"),
    path("fee-categories/create/", views.fee_category_create, name="fee_category_create"),
    path("fee-categories/<int:pk>/edit/", views.fee_category_update, name="fee_category_update"),
    path("fee-categories/<int:pk>/delete/", views.fee_category_delete, name="fee_category_delete"),
    path("batches/", views.batch_list, name="batch_list"),
    path("batches/create/", views.batch_create, name="batch_create"),
    path("batches/<int:pk>/edit/", views.batch_update, name="batch_update"),
    path("batches/<int:pk>/delete/", views.batch_delete, name="batch_delete"),
    path("leads/", views.lead_list, name="lead_list"),
    path("leads/create/", views.lead_create, name="lead_create"),
    path("leads/<int:pk>/edit/", views.lead_update, name="lead_update"),
    path("leads/<int:pk>/delete/", views.lead_delete, name="lead_delete"),
    path("leads/<int:pk>/convert/", views.lead_convert, name="lead_convert"),
    path("visitors/", views.visitor_list, name="visitor_list"),
    path("visitors/create/", views.visitor_create, name="visitor_create"),
    path("visitors/<int:pk>/edit/", views.visitor_update, name="visitor_update"),
    path("visitors/<int:pk>/delete/", views.visitor_delete, name="visitor_delete"),
    path("users/", views.user_list, name="user_list"),
    path("users/create/", views.user_create, name="user_create"),
    path("users/<int:pk>/edit/", views.user_update, name="user_update"),
    path("users/<int:pk>/delete/", views.user_delete, name="user_delete"),
    path("students/", views.student_list, name="student_list"),
    path("students/template/", views.student_import_template, name="student_import_template"),
    path("students/import/validate/", views.student_bulk_import_validate, name="student_bulk_import_validate"),
    path("students/import/", views.student_bulk_import, name="student_bulk_import"),
    path("students/export/", views.student_export, name="student_export"),
    path("students/promote/", views.student_promote, name="student_promote"),
    path("students/create/", views.student_create, name="student_create"),
    path("students/bulk-delete/", views.student_bulk_delete, name="student_bulk_delete"),
    path("students/<int:pk>/", views.student_dashboard, name="student_dashboard"),
    path("students/<int:pk>/add-fee/", views.student_add_fee, name="student_add_fee"),
    path("students/<int:pk>/receive-fee/", views.student_receive_fee, name="student_receive_fee"),
    path("students/<int:pk>/edit/", views.student_update, name="student_update"),
    path("students/<int:pk>/edit-basic/", views.student_basic_update, name="student_basic_update"),
    path("students/<int:pk>/edit-education/", views.student_education_update, name="student_education_update"),
    path("students/<int:pk>/edit-guardian/", views.student_guardian_update, name="student_guardian_update"),
    path("students/<int:pk>/documents/upload/", views.student_document_upload, name="student_document_upload"),
    path("students/<int:pk>/delete/", views.student_delete, name="student_delete"),
    path("student-documents/<int:pk>/delete/", views.student_document_delete, name="student_document_delete"),
    path("payments/<int:pk>/receipt/", views.payment_receipt, name="payment_receipt"),
    path("payments/<int:pk>/edit/", views.payment_update, name="payment_update"),
    path("payments/<int:pk>/void/", views.payment_void, name="payment_void"),
    path("enrollments/", views.enrollment_list, name="enrollment_list"),
    path("enrollments/create/", views.enrollment_create, name="enrollment_create"),
    path("enrollments/<int:pk>/edit/", views.enrollment_update, name="enrollment_update"),
    path("enrollments/<int:pk>/delete/", views.enrollment_delete, name="enrollment_delete"),
    path("homework/", views.homework_list, name="homework_list"),
    path("homework/create/", views.homework_create, name="homework_create"),
    path("homework/<int:pk>/edit/", views.homework_update, name="homework_update"),
    path("homework/<int:pk>/delete/", views.homework_delete, name="homework_delete"),
    path("attendance/", views.attendance_list, name="attendance_list"),
    path("attendance/export/", views.attendance_export, name="attendance_export"),
    path("notices/", views.notice_list, name="notice_list"),
    path("notices/create/", views.notice_create, name="notice_create"),
    path("notices/<int:pk>/edit/", views.notice_update, name="notice_update"),
    path("notices/<int:pk>/delete/", views.notice_delete, name="notice_delete"),
    path("teachers/", views.teacher_list, name="teacher_list"),
    path("teachers/create/", views.teacher_create, name="teacher_create"),
    path("teachers/<int:pk>/edit/", views.teacher_update, name="teacher_update"),
    path("teachers/<int:pk>/delete/", views.teacher_delete, name="teacher_delete"),

    path("exams/", views.exams, name="institute_exams"),
    path("exams/create/", views.exam_create, name="institute_exam_create"),
    path("exams/<int:pk>/edit/", views.exam_update, name="institute_exam_update"),
    path("exams/<int:pk>/questions/", views.exam_questions, name="institute_exam_questions"),
    path("exams/<int:pk>/questions/create/", views.exam_question_create, name="institute_exam_question_create"),
    path("exams/<int:pk>/questions/import/", views.exam_question_bulk_import, name="institute_exam_question_bulk_import"),
    path(
        "exams/<int:pk>/questions/import-template/",
        views.exam_question_import_template,
        name="institute_exam_question_import_template",
    ),
    path(
        "exams/<int:exam_pk>/questions/<int:question_pk>/edit/",
        views.exam_question_update,
        name="institute_exam_question_update",
    ),
    path("exams/<int:pk>/submissions/", views.exam_submissions, name="institute_exam_submissions"),
    path("exams/<int:pk>/publish/", views.exam_publish, name="institute_exam_publish"),
    path(
        "exams/<int:exam_pk>/submissions/<int:attempt_pk>/manage/",
        views.exam_attempt_manage,
        name="institute_exam_attempt_manage",
    ),
    path(
        "exams/<int:exam_pk>/submissions/<int:attempt_pk>/reset/",
        views.exam_attempt_reset,
        name="institute_exam_attempt_reset",
    ),
    path("exams/<int:pk>/results/visibility/", views.exam_toggle_result_publish, name="institute_exam_toggle_result_publish"),
    path("results/", views.results, name="institute_results"),
    path("results/create/", views.result_create, name="institute_result_create"),
]
