# Generated by Django 6.0.5 on 2026-07-17 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCMPartner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('CONNECTED', 'Connected'), ('NOT_CONNECTED', 'Not connected'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not interested'), ('CALL_LATER', 'Call later')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_history', to='UCMPartner.partnerlead')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_history', to='UCMPartner.partnerprofile')),
            ],
            options={
                'verbose_name': 'Partner call history',
                'verbose_name_plural': 'Partner call history',
                'ordering': ['-call_time', '-created_at'],
                'indexes': [models.Index(fields=['partner', '-call_time'], name='call_partner_time_idx'), models.Index(fields=['lead', '-call_time'], name='call_lead_time_idx')],
            },
        ),
    ]
