# Generated by Django 6.0.5 on 2026-07-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCMPartner', '0002_partnercallhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlead',
            name='priority',
            field=models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold')], default='WARM', max_length=10),
        ),
        migrations.AddIndex(
            model_name='partnerlead',
            index=models.Index(fields=['partner', 'priority'], name='lead_partner_priority_idx'),
        ),
    ]
