# Generated by Django 6.0.5 on 2026-07-18 13:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCMPartner', '0003_partnerlead_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSaleClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('commission_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('payment_screenshot', models.ImageField(upload_to='partner_sale_claims/screenshots/')),
                ('payment_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_claim', to='UCMPartner.partnerlead')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_claims', to='UCMPartner.partnerprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['partner', 'status'], name='claim_partner_status_idx'), models.Index(fields=['submitted_at'], name='claim_submitted_idx')],
            },
        ),
    ]
