# Generated by Django 6.0.5 on 2026-07-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCMPartner', '0004_partnersaleclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercommission',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
