# Generated by Django 6.0.5 on 2026-07-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCMPartner', '0005_partnercommission_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='google_pay_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='phonepe_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
