# Generated by Django 6.0.5 on 2026-06-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='institution_size',
            field=models.CharField(blank=True, choices=[('1-25', 'Up to 100 students'), ('26-75', '100-500 students'), ('76-150', '500-1000 students'), ('150+', '1000+ students')], max_length=20),
        ),
    ]
