# Generated by Django 6.0.5 on 2026-07-03 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_contactenquiry_institution_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('institute', models.CharField(blank=True, max_length=180, verbose_name='School or institute')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(max_length=1000)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Website feedback',
                'verbose_name_plural': 'Website feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
