# Generated by Django 6.0.5 on 2026-07-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_websitefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('sales_executive', 'Sales Executive'), ('backend_developer', 'Backend Developer'), ('frontend_developer', 'Frontend Developer'), ('tester', 'Tester'), ('flutter_developer', 'Flutter Developer'), ('support_executive', 'Support Executive'), ('other', 'Other')], default='sales_executive', max_length=40)),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('0-1', '0-1 year'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5+', '5+ years')], max_length=20)),
                ('qualification', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=100)),
                ('current_company', models.CharField(blank=True, max_length=160)),
                ('expected_salary', models.CharField(blank=True, max_length=80)),
                ('notice_period', models.CharField(blank=True, max_length=80)),
                ('resume_link', models.URLField(blank=True)),
                ('portfolio_link', models.URLField(blank=True)),
                ('cover_letter', models.TextField(blank=True, max_length=1500)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career application',
                'verbose_name_plural': 'Career applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
