# Generated by Django 6.0.5 on 2026-07-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_careerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerapplication',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='resume_link',
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='resume',
            field=models.FileField(default='', upload_to='career_resumes/'),
        ),
    ]
