# Generated by Django 6.0.5 on 2026-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_remove_careerapplication_current_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='role',
            field=models.CharField(choices=[('sales_executive', 'Sales Executive')], max_length=40),
        ),
    ]
