# Generated by Django 6.0.5 on 2026-06-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_alter_institute_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteRegistration',
            fields=[
            ],
            options={
                'verbose_name': 'Institute registration',
                'verbose_name_plural': 'Institute registrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('super_admin.userprofile',),
        ),
    ]
