# Generated by Django 6.0.5 on 2026-06-07 09:05

import django.db.models.deletion
from django.db import migrations, models


def simplify_subscription_data(apps, schema_editor):
    InstituteSubscription = apps.get_model("super_admin", "InstituteSubscription")
    SubscriptionPayment = apps.get_model("super_admin", "SubscriptionPayment")

    for subscription in InstituteSubscription.objects.all():
        subscription.starts_on = subscription.starts_on or subscription.current_period_starts_on
        subscription.ends_on = (
            subscription.current_period_ends_on
            or subscription.ends_on
            or subscription.trial_ends_on
        )
        subscription.save(update_fields=["starts_on", "ends_on"])

    for payment in SubscriptionPayment.objects.select_related("invoice"):
        payment.institute_id = payment.invoice.institute_id
        payment.save(update_fields=["institute"])


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0006_userprofile_onboarding_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='super_admin.institute'),
        ),
        migrations.RunPython(simplify_subscription_data, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='subscriptioninvoice',
            name='saas_inv_inst_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscriptioninvoice',
            name='saas_inv_status_due_idx',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='institutesubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='institutesubscription',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='institutesubscription',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='institutesubscription',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='institutesubscription',
            name='current_period_ends_on',
        ),
        migrations.RemoveField(
            model_name='institutesubscription',
            name='current_period_starts_on',
        ),
        migrations.RemoveField(
            model_name='institutesubscription',
            name='external_subscription_id',
        ),
        migrations.RemoveField(
            model_name='institutesubscription',
            name='status',
        ),
        migrations.RemoveField(
            model_name='institutesubscription',
            name='trial_ends_on',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='external_payment_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='status',
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank transfer'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='SubscriptionInvoice',
        ),
    ]
