# Generated by Django 6.0.5 on 2026-06-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0008_alter_subscriptionpayment_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutesubscription',
            name='plan',
            field=models.CharField(choices=[('FREE_TRIAL', 'Free Trial'), ('PREMIUM', 'Premium')], default='FREE_TRIAL', max_length=20),
        ),
    ]
