# Generated by Django 6.0.5 on 2026-06-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0009_institutesubscription_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ['name'], 'verbose_name': 'Institute account', 'verbose_name_plural': 'Institute accounts'},
        ),
        migrations.AlterModelOptions(
            name='institutesubscription',
            options={'ordering': ['institute__name'], 'verbose_name': 'Software subscription', 'verbose_name_plural': 'Software subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionpayment',
            options={'ordering': ['-paid_on', '-pk'], 'verbose_name': 'Subscription payment', 'verbose_name_plural': 'Subscription payment history'},
        ),
        migrations.AlterField(
            model_name='institute',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='TRIAL', help_text='Use Active or Trial to allow access. Suspended and Cancelled block access.', max_length=20),
        ),
        migrations.AlterField(
            model_name='institutesubscription',
            name='ends_on',
            field=models.DateField(blank=True, help_text='Access is blocked automatically after this date.', null=True, verbose_name='Access expiry date'),
        ),
        migrations.AlterField(
            model_name='institutesubscription',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional internal notes about renewal or subscription.'),
        ),
        migrations.AlterField(
            model_name='institutesubscription',
            name='plan',
            field=models.CharField(choices=[('FREE_TRIAL', 'Free Trial'), ('PREMIUM', 'Premium')], default='FREE_TRIAL', help_text='Choose Free Trial for trial access or Premium for paid access.', max_length=20),
        ),
        migrations.AlterField(
            model_name='institutesubscription',
            name='starts_on',
            field=models.DateField(blank=True, help_text='The school can use the software from this date.', null=True, verbose_name='Access start date'),
        ),
    ]
