# Generated by Django 6.0.5 on 2026-06-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0010_alter_institute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, upload_to='institutes/logos/'),
        ),
    ]
