# Generated by Django 6.0.5 on 2026-06-23 01:33

import super_admin.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0012_institute_institute_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, upload_to=super_admin.media_utils.institute_logo_upload_path),
        ),
    ]
