# Generated by Django 6.0.5 on 2026-06-26 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0013_alter_institute_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['institute', 'role'], name='profile_inst_role_idx'),
        ),
    ]
