# Generated by Django 6.0.5 on 2026-07-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0015_institute_status_login_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('INSTITUTE_ADMIN', 'Institute Admin'), ('TEACHER', 'Teacher'), ('ACCOUNTANT', 'Accountant'), ('STUDENT_PARENT', 'Student/Parent'), ('UCM_PARTNER', 'UCM Partner')], max_length=30),
        ),
    ]
