# Generated by Django 6.0.5 on 2026-05-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='course',
        ),
        migrations.AddField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(related_name='batches', to='institute_admin.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
