# Generated by Django 6.0.5 on 2026-05-27 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0002_remove_batch_course_batch_courses_course_fee_amount'),
        ('student_parent', '0003_studentprofile_current_school_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pin_on_top', '-created_at']},
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ACADEMIC', 'Academic'), ('FEES', 'Fees'), ('EXAM', 'Exam'), ('EVENT', 'Event'), ('HOLIDAY', 'Holiday'), ('URGENT', 'Urgent')], default='GENERAL', max_length=30),
        ),
        migrations.AddField(
            model_name='notice',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='pin_on_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='push_to_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_batches',
            field=models.ManyToManyField(blank=True, related_name='notices', to='institute_admin.batch'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_courses',
            field=models.ManyToManyField(blank=True, related_name='notices', to='institute_admin.course'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_students',
            field=models.ManyToManyField(blank=True, related_name='notices', to='student_parent.studentprofile'),
        ),
        migrations.CreateModel(
            name='NoticeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='institute_admin.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
                'unique_together': {('notice', 'user')},
            },
        ),
    ]
