# Generated by Django 6.0.5 on 2026-05-27 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0003_alter_notice_options_notice_category_and_more'),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='super_admin.institute')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('institute', 'name')},
            },
        ),
    ]
