# Generated by Django 6.0.5 on 2026-06-03 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0006_course_batch_academic_year'),
        ('student_parent', '0011_userdevice_pushnotification'),
        ('super_admin', '0002_mobilerefreshtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['institute', 'is_active', '-start_date'], name='ay_inst_active_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['institute', 'academic_year', 'is_active'], name='batch_inst_year_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['institute', 'academic_year', 'is_active'], name='course_inst_year_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['institute', 'is_published', 'push_to_app', '-pin_on_top', '-created_at'], name='notice_app_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['institute', 'category', '-created_at'], name='notice_category_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['institute', 'priority', '-created_at'], name='notice_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='noticeread',
            index=models.Index(fields=['user', '-read_at'], name='notice_read_user_idx'),
        ),
    ]
