# Generated by Django 6.0.5 on 2026-06-03 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0007_academicyear_ay_inst_active_idx_and_more'),
        ('super_admin', '0002_mobilerefreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='institute_admin.academicyear')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='super_admin.institute')),
            ],
            options={
                'ordering': ['academic_year__start_date', 'name'],
                'indexes': [models.Index(fields=['institute', 'academic_year', 'is_active'], name='subject_inst_year_idx')],
                'unique_together': {('institute', 'academic_year', 'name')},
            },
        ),
    ]
