# Generated by Django 6.0.5 on 2026-06-07 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0014_update_visitor_log_fields'),
        ('super_admin', '0010_alter_institute_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACCOUNT', 'Account and login'), ('BILLING', 'Subscription and billing'), ('SETUP', 'Institute setup'), ('STUDENTS', 'Students and admissions'), ('FEES', 'Fees and payments'), ('ATTENDANCE', 'Attendance'), ('EXAMS', 'Exams and results'), ('TECHNICAL', 'Technical issue'), ('OTHER', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='super_admin.institute')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institute', 'status', '-created_at'], name='support_inst_status_idx')],
            },
        ),
    ]
