# Generated by Django 6.0.5 on 2026-06-23 01:33

import super_admin.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0020_global_print_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='input_file',
            field=models.FileField(blank=True, upload_to=super_admin.media_utils.background_job_input_upload_path),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='attachment',
            field=models.FileField(blank=True, upload_to=super_admin.media_utils.visitor_attachment_upload_path, verbose_name='Attachment / ID Scan'),
        ),
    ]
