# Generated by Django 6.0.5 on 2026-06-27 01:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_lead_academic_year(apps, schema_editor):
    AcademicYear = apps.get_model("institute_admin", "AcademicYear")
    Lead = apps.get_model("institute_admin", "Lead")

    for lead in Lead.objects.select_related("interested_class", "interested_batch").filter(academic_year__isnull=True):
        academic_year = None
        if lead.interested_class_id:
            academic_year = lead.interested_class.academic_year
        elif lead.interested_batch_id:
            academic_year = lead.interested_batch.academic_year

        if academic_year is None and lead.created_at:
            created_on = lead.created_at.date()
            academic_year = (
                AcademicYear.objects.filter(
                    institute_id=lead.institute_id,
                    start_date__lte=created_on,
                    end_date__gte=created_on,
                )
                .order_by("-start_date", "-pk")
                .first()
            )

        if academic_year is None:
            academic_year = (
                AcademicYear.objects.filter(institute_id=lead.institute_id, is_active=True)
                .order_by("-start_date", "-pk")
                .first()
                or AcademicYear.objects.filter(institute_id=lead.institute_id)
                .order_by("-start_date", "-pk")
                .first()
            )

        if academic_year is not None:
            lead.academic_year_id = academic_year.pk
            lead.save(update_fields=["academic_year"])


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0024_notice_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='institute_admin.academicyear'),
        ),
        migrations.RunPython(backfill_lead_academic_year, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['institute', 'academic_year', 'status'], name='lead_inst_year_status_idx'),
        ),
    ]
