# Generated by Codex on 2026-07-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("super_admin", "0014_userprofile_profile_inst_role_idx"),
        ("institute_admin", "0025_lead_academic_year_lead_lead_inst_year_status_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("student_admission", "Student Admission Report"),
                            ("inactive_students", "Inactive / Left Students Report"),
                            ("profit_loss", "Finance Report Dashboard"),
                            ("fee_collection", "Fees Report Dashboard"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("criteria", models.JSONField(blank=True, default=dict)),
                ("query_string", models.CharField(blank=True, max_length=1000)),
                ("generation_count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_generated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="super_admin.institute",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_generated_at"],
                "unique_together": {("institute", "created_by", "report_type", "query_string")},
                "indexes": [
                    models.Index(fields=["institute", "-last_generated_at"], name="genrep_inst_last_idx"),
                    models.Index(fields=["institute", "report_type"], name="genrep_inst_type_idx"),
                ],
            },
        ),
    ]
