# Generated by Django 6.0.5 on 2026-05-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
        ('institute_admin', '0002_remove_batch_course_batch_courses_course_fee_amount'),
        ('student_parent', '0002_remove_studentprofile_batch_studentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinvoice',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_invoices', to='institute_admin.batch'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_invoices', to='institute_admin.course'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_invoices', to='student_parent.studentenrollment'),
        ),
    ]
