# Generated by Django 6.0.5 on 2026-05-26 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_feeinvoice_batch_feeinvoice_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('VOIDED', 'Voided')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='void_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('VOIDED', 'Voided')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_method', models.CharField(blank=True, max_length=30)),
                ('new_method', models.CharField(blank=True, max_length=30)),
                ('old_receipt_number', models.CharField(blank=True, max_length=60)),
                ('new_receipt_number', models.CharField(blank=True, max_length=60)),
                ('note', models.CharField(max_length=255)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accountant.payment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
