# Generated by Django 6.0.5 on 2026-05-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0003_payment_created_at_payment_status_and_more'),
        ('student_parent', '0007_copy_students_to_academic_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinvoice',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='student_parent.studentacademicsession'),
        ),
    ]
