# Generated by Django 6.0.5 on 2026-05-28 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0004_feeinvoice_academic_session'),
        ('student_parent', '0009_alter_studentenrollment_academic_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeinvoice',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='student_parent.studentacademicsession'),
        ),
    ]
