# Generated by Django 6.0.5 on 2026-06-03 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0005_alter_feeinvoice_academic_session'),
        ('institute_admin', '0006_course_batch_academic_year'),
        ('student_parent', '0011_userdevice_pushnotification'),
        ('super_admin', '0002_mobilerefreshtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['institute', '-spent_on'], name='expense_inst_date_idx'),
        ),
        migrations.AddIndex(
            model_name='feecategory',
            index=models.Index(fields=['institute', 'is_active', 'name'], name='feecat_inst_active_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['academic_session', 'status', '-due_date'], name='inv_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['student', 'status', '-due_date'], name='inv_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['institute', 'status', '-due_date'], name='inv_inst_status_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['enrollment', 'status'], name='inv_enroll_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status', '-paid_on'], name='pay_invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-paid_on'], name='pay_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='pay_receipt_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentactivity',
            index=models.Index(fields=['payment', '-performed_at'], name='payact_payment_time_idx'),
        ),
    ]
