# Generated by Django 6.0.5 on 2026-06-12 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0006_expense_expense_inst_date_idx_and_more'),
        ('institute_admin', '0016_backgroundjob'),
        ('student_parent', '0012_guardianprofile_guardian_primary_idx_and_more'),
        ('super_admin', '0010_alter_institute_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['academic_session', '-due_date'], name='inv_session_due_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at', '-id'], name='pay_status_created_idx'),
        ),
    ]
