# Generated by Codex on 2026-06-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accountant", "0007_feeinvoice_inv_session_due_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="expenses/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accountant.expense",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="expensedocument",
            index=models.Index(fields=["expense", "-uploaded_at"], name="expdoc_expense_time_idx"),
        ),
    ]
