# Generated by Django 6.0.5 on 2026-06-23 01:33

import super_admin.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0008_expensedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedocument',
            name='file',
            field=models.FileField(upload_to=super_admin.media_utils.expense_document_upload_path),
        ),
    ]
