# Generated by Django 6.0.5 on 2026-07-03 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0010_fee_category_expense_academic_year'),
        ('institute_admin', '0026_generatedreport'),
        ('super_admin', '0014_userprofile_profile_inst_role_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('old_title', models.CharField(blank=True, max_length=160)),
                ('new_title', models.CharField(blank=True, max_length=160)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_spent_on', models.DateField(blank=True, null=True)),
                ('new_spent_on', models.DateField(blank=True, null=True)),
                ('old_note', models.CharField(blank=True, max_length=255)),
                ('new_note', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_activities', to='institute_admin.academicyear')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='accountant.expense')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_activities', to='super_admin.institute')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['expense', '-performed_at'], name='expact_expense_time_idx'), models.Index(fields=['institute', 'academic_year', '-performed_at'], name='expact_inst_year_time_idx'), models.Index(fields=['action', '-performed_at'], name='expact_action_time_idx')],
            },
        ),
    ]
