# Generated by Django 6.0.5 on 2026-07-03 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0011_expenseactivity'),
        ('institute_admin', '0026_generatedreport'),
        ('super_admin', '0014_userprofile_profile_inst_role_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_expense_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_on', models.DateField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_bin_records', to='institute_admin.academicyear')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_expenses', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_bin_records', to='super_admin.institute')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_deleted_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.AddField(
            model_name='expenseactivity',
            name='expense_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='accountant.expensebin'),
        ),
        migrations.AddIndex(
            model_name='expensebin',
            index=models.Index(fields=['institute', 'academic_year', '-deleted_at'], name='expbin_inst_year_time_idx'),
        ),
        migrations.AddIndex(
            model_name='expensebin',
            index=models.Index(fields=['original_expense_id'], name='expbin_original_idx'),
        ),
    ]
