# Generated by Django 6.0.5 on 2026-05-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0002_remove_batch_course_batch_courses_course_fee_amount'),
        ('student_parent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='batch',
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('custom_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='institute_admin.batch')),
                ('courses', models.ManyToManyField(blank=True, related_name='student_enrollments', to='institute_admin.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student_parent.studentprofile')),
            ],
            options={
                'ordering': ['student__admission_number', 'batch__name'],
                'unique_together': {('student', 'batch')},
            },
        ),
    ]
