# Generated by Django 6.0.5 on 2026-05-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_parent', '0002_remove_studentprofile_batch_studentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_school_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_school_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='previous_class',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='previous_school_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='students/profile_images/'),
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PROFILE', 'Profile'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('MARKSHEET', 'Marksheet'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='students/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student_parent.studentprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
