# Generated by Django 6.0.5 on 2026-05-27 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0004_academicyear'),
        ('student_parent', '0003_studentprofile_current_school_address_and_more'),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='institute_admin.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('institute', 'academic_year', 'admission_number')},
        ),
    ]
