# Generated by Django 6.0.5 on 2026-05-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0004_academicyear'),
        ('student_parent', '0005_assign_existing_students_academic_year'),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=40)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('LEFT', 'Left'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('current_school_name', models.CharField(blank=True, max_length=160)),
                ('current_school_address', models.TextField(blank=True)),
                ('previous_school_name', models.CharField(blank=True, max_length=160)),
                ('previous_class', models.CharField(blank=True, max_length=80)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_sessions', to='institute_admin.academicyear')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_academic_sessions', to='super_admin.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='student_parent.studentprofile')),
            ],
            options={
                'ordering': ['academic_year__name', 'admission_number'],
                'unique_together': {('institute', 'academic_year', 'admission_number'), ('student', 'academic_year')},
            },
        ),
    ]
