# Generated by Django 6.0.5 on 2026-05-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0004_academicyear'),
        ('student_parent', '0007_copy_students_to_academic_sessions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['academic_session__admission_number', 'student__admission_number', 'batch__name']},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student_parent.studentacademicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('academic_session', 'batch')},
        ),
    ]
