# Generated by Django 6.0.5 on 2026-05-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_parent', '0009_alter_studentenrollment_academic_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['academic_session__admission_number', 'batch__name']},
        ),
    ]
