# Generated by Django 6.0.5 on 2026-06-03 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0007_academicyear_ay_inst_active_idx_and_more'),
        ('student_parent', '0011_userdevice_pushnotification'),
        ('super_admin', '0002_mobilerefreshtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guardianprofile',
            index=models.Index(fields=['student', 'is_primary'], name='guardian_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['user', '-created_at'], name='push_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['user', 'status', '-created_at'], name='push_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentacademicsession',
            index=models.Index(fields=['student', 'status'], name='sas_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentacademicsession',
            index=models.Index(fields=['institute', 'academic_year', 'status'], name='sas_inst_year_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['student', '-uploaded_at'], name='stud_doc_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', 'status'], name='se_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['academic_session', 'status'], name='se_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['batch', 'status'], name='se_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['institute', 'academic_year', 'is_active'], name='sp_inst_year_active_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['institute', 'admission_number'], name='sp_inst_adm_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_active', '-last_seen_at'], name='device_user_active_idx'),
        ),
    ]
