# Generated by Django 6.0.5 on 2026-06-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0016_backgroundjob'),
        ('student_parent', '0012_guardianprofile_guardian_primary_idx_and_more'),
        ('super_admin', '0010_alter_institute_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentacademicsession',
            index=models.Index(fields=['institute', 'academic_year', 'status', 'admission_number'], name='sas_scope_status_adm_idx'),
        ),
    ]
