from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_parent", "0014_pushnotification_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="gr_number_udise",
            field=models.CharField(blank=True, max_length=80, verbose_name="GR Number / UDISE Number"),
        ),
        migrations.AddField(model_name="studentprofile", name="roll_number", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="studentprofile", name="middle_name", field=models.CharField(blank=True, max_length=150)),
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(blank=True, choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")], max_length=20),
        ),
        migrations.AddField(model_name="studentprofile", name="blood_group", field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name="studentprofile", name="religion", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="studentprofile", name="caste_category", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="studentprofile", name="nationality", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="studentprofile", name="aadhaar_number", field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name="studentprofile", name="birth_certificate_number", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="studentprofile", name="place_of_birth", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="mother_tongue", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="studentprofile", name="father_name", field=models.CharField(blank=True, max_length=160)),
        migrations.AddField(model_name="studentprofile", name="father_occupation", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="father_qualification", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="father_mobile_number", field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name="studentprofile", name="father_email", field=models.EmailField(blank=True, max_length=254)),
        migrations.AddField(model_name="studentprofile", name="father_aadhaar_number", field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name="studentprofile", name="father_annual_income", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="studentprofile", name="mother_name", field=models.CharField(blank=True, max_length=160)),
        migrations.AddField(model_name="studentprofile", name="mother_occupation", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="mother_qualification", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="mother_mobile_number", field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name="studentprofile", name="mother_aadhaar_number", field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name="studentprofile", name="mother_annual_income", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="studentprofile", name="guardian_address", field=models.TextField(blank=True)),
        migrations.AddField(model_name="studentprofile", name="current_house_number", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="studentprofile", name="current_street_area", field=models.CharField(blank=True, max_length=160)),
        migrations.AddField(model_name="studentprofile", name="current_village_city", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="current_taluka", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="current_district", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="current_state", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="current_pin_code", field=models.CharField(blank=True, max_length=12)),
        migrations.AddField(model_name="studentprofile", name="permanent_house_number", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="studentprofile", name="permanent_street_area", field=models.CharField(blank=True, max_length=160)),
        migrations.AddField(model_name="studentprofile", name="permanent_village_city", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="permanent_taluka", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="permanent_district", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="permanent_state", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="permanent_pin_code", field=models.CharField(blank=True, max_length=12)),
        migrations.AddField(model_name="studentprofile", name="admission_class", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="studentprofile", name="current_class", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="studentprofile", name="division", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="studentprofile", name="medium", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="studentprofile", name="previous_school_address", field=models.TextField(blank=True)),
        migrations.AddField(model_name="studentprofile", name="previous_school_udise_code", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="studentprofile", name="previous_class_passed", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="studentprofile", name="last_exam_result", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="studentprofile", name="result", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="studentprofile", name="conduct", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentprofile", name="reason_for_leaving", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="studentprofile", name="date_of_leaving_school", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="studentprofile", name="tc_issue_date", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="studentprofile", name="bonafide_purpose", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="studentprofile", name="emergency_contact_number", field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(
            model_name="studentprofile",
            name="student_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("TC_ISSUED", "TC Issued"),
                    ("LEFT_SCHOOL", "Left School"),
                    ("PASSED_OUT", "Passed Out"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("STUDENT_PHOTO", "Student Photo"),
                    ("BIRTH_CERTIFICATE", "Birth Certificate"),
                    ("AADHAAR", "Aadhaar"),
                    ("PARENT_AADHAAR", "Parent Aadhaar"),
                    ("CASTE_CERTIFICATE", "Caste Certificate"),
                    ("INCOME_CERTIFICATE", "Income Certificate"),
                    ("PROFILE", "Profile"),
                    ("TRANSFER_CERTIFICATE", "Transfer Certificate"),
                    ("LEAVING_CERTIFICATE", "Leaving Certificate"),
                    ("BONAFIDE_CERTIFICATE", "Bonafide Certificate"),
                    ("ADDRESS_PROOF", "Address Proof"),
                    ("MARKSHEET", "Marksheet"),
                    ("PASSPORT_PHOTOS", "Passport Size Photos"),
                    ("DISABILITY_CERTIFICATE", "Disability Certificate"),
                    ("MIGRATION_CERTIFICATE", "Migration Certificate"),
                    ("RTE_DOCUMENTS", "RTE Documents"),
                    ("BANK_PASSBOOK", "Bank Passbook"),
                    ("VACCINATION_RECORD", "Vaccination Record"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=40,
            ),
        ),
    ]
