# Generated by Django 6.0.5 on 2026-06-23 01:33

import super_admin.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_parent', '0019_studentprofile_udise_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(upload_to=super_admin.media_utils.student_document_upload_path),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=super_admin.media_utils.student_profile_image_upload_path),
        ),
    ]
