# Generated by Django 6.0.5 on 2026-07-19 15:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute_admin', '0026_generatedreport'),
        ('student_parent', '0022_simplify_student_status'),
        ('super_admin', '0016_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('STRUCTURE_READY', 'Structure ready'), ('MARKS_ENTRY_OPEN', 'Marks entry open'), ('MARKS_ENTRY_COMPLETED', 'Marks entry completed'), ('GENERATED', 'Generated'), ('PUBLISHED', 'Published'), ('LOCKED', 'Locked')], default='DRAFT', max_length=30)),
                ('institute_name_snapshot', models.CharField(blank=True, max_length=160)),
                ('academic_year_name_snapshot', models.CharField(blank=True, max_length=20)),
                ('batch_name_snapshot', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_assessments', to='institute_admin.academicyear')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_assessments', to='institute_admin.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_card_assessments', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_assessments', to='super_admin.institute')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_report_card_assessments', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_report_card_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardAssessmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name_snapshot', models.CharField(blank=True, max_length=120)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('passing_marks', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('weightage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_optional', models.BooleanField(default=False)),
                ('include_in_total', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_subjects', to='report_card.reportcardassessment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_assessment_subjects', to='institute_admin.subject')),
            ],
            options={
                'ordering': ['display_order', 'subject_name_snapshot', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ASSESSMENT_CREATED', 'Assessment created'), ('ASSESSMENT_UPDATED', 'Assessment updated'), ('STRUCTURE_CHANGED', 'Structure changed'), ('MARKS_ENTRY_OPENED', 'Marks entry opened'), ('MARKS_SAVED', 'Marks saved'), ('RESULTS_GENERATED', 'Results generated'), ('RESULTS_PUBLISHED', 'Results published'), ('ASSESSMENT_LOCKED', 'Assessment locked'), ('ASSESSMENT_UNLOCKED', 'Assessment unlocked')], max_length=40)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_card_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='report_card.reportcardassessment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardGradeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(max_length=20)),
                ('remark', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_card_grade_rules', to='institute_admin.academicyear')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_grade_rules', to='super_admin.institute')),
            ],
            options={
                'ordering': ['display_order', '-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardMarkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_absent', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('student_name_snapshot', models.CharField(blank=True, max_length=180)),
                ('admission_number_snapshot', models.CharField(blank=True, max_length=40)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_mark_entries', to='student_parent.studentacademicsession')),
                ('assessment_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='report_card.reportcardassessmentsubject')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_report_card_marks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_mark_entries', to='student_parent.studentprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_card_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['academic_session__admission_number', 'student__user__first_name', 'student__user__username'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardStudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_obtained', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('total_max_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('weighted_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('total_weightage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('result_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('INCOMPLETE', 'Incomplete'), ('ABSENT', 'Absent')], default='INCOMPLETE', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('is_stale', models.BooleanField(default=False)),
                ('student_name_snapshot', models.CharField(blank=True, max_length=180)),
                ('admission_number_snapshot', models.CharField(blank=True, max_length=40)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_results', to='student_parent.studentacademicsession')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='report_card.reportcardassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_results', to='student_parent.studentprofile')),
            ],
            options={
                'ordering': ['rank', '-percentage', 'admission_number_snapshot'],
            },
        ),
        migrations.AddIndex(
            model_name='reportcardassessment',
            index=models.Index(fields=['institute', 'academic_year', 'status'], name='rc_assess_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardassessment',
            index=models.Index(fields=['batch', 'status', '-created_at'], name='rc_assess_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardassessment',
            index=models.Index(fields=['created_by', '-created_at'], name='rc_assess_creator_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcardassessment',
            constraint=models.UniqueConstraint(fields=('institute', 'academic_year', 'batch', 'title'), name='rc_assessment_unique_title'),
        ),
        migrations.AddIndex(
            model_name='reportcardassessmentsubject',
            index=models.Index(fields=['assessment', 'display_order'], name='rc_subject_order_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardassessmentsubject',
            index=models.Index(fields=['subject'], name='rc_subject_master_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcardassessmentsubject',
            constraint=models.UniqueConstraint(fields=('assessment', 'subject'), name='rc_subject_unique_subject'),
        ),
        migrations.AddConstraint(
            model_name='reportcardassessmentsubject',
            constraint=models.UniqueConstraint(fields=('assessment', 'display_order'), name='rc_subject_unique_order'),
        ),
        migrations.AddIndex(
            model_name='reportcardauditlog',
            index=models.Index(fields=['assessment', '-created_at'], name='rc_audit_assess_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardauditlog',
            index=models.Index(fields=['actor', '-created_at'], name='rc_audit_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardauditlog',
            index=models.Index(fields=['action', '-created_at'], name='rc_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardgraderule',
            index=models.Index(fields=['institute', 'academic_year', 'is_active'], name='rc_grade_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardgraderule',
            index=models.Index(fields=['min_percentage', 'max_percentage'], name='rc_grade_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcardgraderule',
            constraint=models.UniqueConstraint(fields=('institute', 'academic_year', 'grade'), name='rc_grade_unique_grade'),
        ),
        migrations.AddIndex(
            model_name='reportcardmarkentry',
            index=models.Index(fields=['assessment_subject', 'is_absent'], name='rc_mark_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardmarkentry',
            index=models.Index(fields=['student', '-updated_at'], name='rc_mark_student_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardmarkentry',
            index=models.Index(fields=['academic_session'], name='rc_mark_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcardmarkentry',
            constraint=models.UniqueConstraint(fields=('assessment_subject', 'academic_session'), name='rc_mark_unique_session'),
        ),
        migrations.AddIndex(
            model_name='reportcardstudentresult',
            index=models.Index(fields=['assessment', 'result_status'], name='rc_result_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardstudentresult',
            index=models.Index(fields=['student', '-generated_at'], name='rc_result_student_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardstudentresult',
            index=models.Index(fields=['assessment', 'rank'], name='rc_result_rank_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcardstudentresult',
            constraint=models.UniqueConstraint(fields=('assessment', 'academic_session'), name='rc_result_unique_session'),
        ),
    ]
