# Generated by Django 6.0.5 on 2026-07-20 14:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0001_initial'),
        ('student_parent', '0022_simplify_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardAssessmentSubjectComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('passing_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('weightage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('include_in_total', models.BooleanField(default=True)),
                ('name_snapshot', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='report_card.reportcardassessmentsubject')),
            ],
            options={
                'ordering': ['display_order', 'name_snapshot', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardComponentMarkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_absent', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('student_name_snapshot', models.CharField(blank=True, max_length=180)),
                ('admission_number_snapshot', models.CharField(blank=True, max_length=40)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_component_mark_entries', to='student_parent.studentacademicsession')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='report_card.reportcardassessmentsubjectcomponent')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_report_card_component_marks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_component_mark_entries', to='student_parent.studentprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_card_component_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['academic_session__admission_number', 'component__display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardSubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name_snapshot', models.CharField(blank=True, max_length=120)),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_optional', models.BooleanField(default=False)),
                ('include_in_total', models.BooleanField(default=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_subject_results', to='student_parent.studentacademicsession')),
                ('assessment_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='report_card.reportcardassessmentsubject')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='report_card.reportcardstudentresult')),
            ],
            options={
                'ordering': ['assessment_subject__display_order', 'subject_name_snapshot'],
            },
        ),
        migrations.AddIndex(
            model_name='reportcardassessmentsubjectcomponent',
            index=models.Index(fields=['assessment_subject', 'display_order'], name='rc_comp_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcardassessmentsubjectcomponent',
            constraint=models.UniqueConstraint(fields=('assessment_subject', 'name'), name='rc_component_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='reportcardassessmentsubjectcomponent',
            constraint=models.UniqueConstraint(fields=('assessment_subject', 'display_order'), name='rc_component_unique_order'),
        ),
        migrations.AddIndex(
            model_name='reportcardcomponentmarkentry',
            index=models.Index(fields=['component', 'is_absent'], name='rc_comp_mark_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardcomponentmarkentry',
            index=models.Index(fields=['student', '-updated_at'], name='rc_comp_mark_student_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardcomponentmarkentry',
            index=models.Index(fields=['academic_session'], name='rc_comp_mark_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcardcomponentmarkentry',
            constraint=models.UniqueConstraint(fields=('component', 'academic_session'), name='rc_comp_mark_unique_session'),
        ),
        migrations.AddIndex(
            model_name='reportcardsubjectresult',
            index=models.Index(fields=['result'], name='rc_subj_result_result_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardsubjectresult',
            index=models.Index(fields=['academic_session'], name='rc_subj_result_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcardsubjectresult',
            constraint=models.UniqueConstraint(fields=('result', 'assessment_subject'), name='rc_subject_result_unique'),
        ),
    ]
