# Generated by Django 6.0.5 on 2026-07-22 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0026_generatedreport'),
        ('report_card', '0002_reportcardassessmentsubjectcomponent_and_more'),
        ('super_admin', '0016_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardTeacherSubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_teacher_subject_allocations', to='institute_admin.academicyear')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_teacher_subject_allocations', to='institute_admin.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_card_subject_allocations', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_teacher_subject_allocations', to='super_admin.institute')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_teacher_subject_allocations', to='institute_admin.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_subject_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['academic_year__start_date', 'batch__name', 'subject__name', 'teacher__username'],
                'indexes': [models.Index(fields=['teacher', 'academic_year'], name='rc_alloc_teacher_year_idx'), models.Index(fields=['batch', 'subject'], name='rc_alloc_batch_subject_idx'), models.Index(fields=['institute', 'academic_year'], name='rc_alloc_inst_year_idx')],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'batch', 'subject', 'teacher'), name='rc_alloc_unique_year_batch_subject_teacher')],
            },
        ),
    ]
