# Generated by Django 6.0.5 on 2026-07-23 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_admin', '0026_generatedreport'),
        ('report_card', '0003_reportcardteachersubjectallocation'),
        ('super_admin', '0016_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportcardassessment',
            name='rc_assessment_unique_title',
        ),
        migrations.AddField(
            model_name='reportcardassessment',
            name='delete_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportcardassessment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcardassessment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_report_card_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcardassessment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='reportcardassessment',
            index=models.Index(fields=['institute', 'is_deleted', 'academic_year'], name='rc_assess_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcardassessment',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='rc_assess_bin_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcardassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('institute', 'academic_year', 'batch', 'title'), name='rc_assessment_unique_title'),
        ),
    ]
