# Generated by Django 6.0.5 on 2026-07-23 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0004_remove_reportcardassessment_rc_assessment_unique_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcardauditlog',
            name='action',
            field=models.CharField(choices=[('ASSESSMENT_CREATED', 'Assessment created'), ('ASSESSMENT_UPDATED', 'Assessment updated'), ('STRUCTURE_CHANGED', 'Structure changed'), ('MARKS_ENTRY_OPENED', 'Marks entry opened'), ('MARKS_SAVED', 'Marks saved'), ('RESULTS_GENERATED', 'Results generated'), ('RESULTS_PUBLISHED', 'Results published'), ('ASSESSMENT_LOCKED', 'Assessment locked'), ('ASSESSMENT_UNLOCKED', 'Assessment unlocked'), ('ASSESSMENT_DELETED', 'Assessment deleted'), ('ASSESSMENT_RESTORED', 'Assessment restored'), ('ASSESSMENT_PERMANENTLY_DELETED', 'Assessment permanently deleted')], max_length=40),
        ),
        migrations.AlterField(
            model_name='reportcardauditlog',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='report_card.reportcardassessment'),
        ),
    ]
