"""
Django settings for UltraCoachMatrix project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--9g_w960n(bzd)lhgg)w0(n)_)^nnc!ldvn@g225=ujrb*zepj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

DEFAULT_ALLOWED_HOSTS = [
    "ultracoachmatrix.pythonanywhere.com",
    "localhost",
    "127.0.0.1",
    "10.0.2.2",
    "10.0.3.2",
    "testserver",
]
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", ",".join(DEFAULT_ALLOWED_HOSTS)).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'super_admin',
    'institute_admin',
    'teacher',
    'accountant',
    'student_parent',
    'Website',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'super_admin.session_middleware.SessionSecurityMetadataMiddleware',
    'super_admin.middleware.InstituteSubscriptionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UltraCoachMatrix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'institute_admin.context_processors.academic_year_context',
                'super_admin.context_processors.subscription_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'UltraCoachMatrix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
WHITENOISE_MAX_AGE = int(os.environ.get("WHITENOISE_MAX_AGE", "31536000"))
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DASHBOARD_CACHE_TIMEOUT = int(os.environ.get("DASHBOARD_CACHE_TIMEOUT", "180"))
LOOKUP_CACHE_TIMEOUT = int(os.environ.get("LOOKUP_CACHE_TIMEOUT", "300"))
STUDENT_EXPORT_CSV_THRESHOLD = int(os.environ.get("STUDENT_EXPORT_CSV_THRESHOLD", "2000"))
STUDENT_IMPORT_BACKGROUND_THRESHOLD = int(os.environ.get("STUDENT_IMPORT_BACKGROUND_THRESHOLD", "500"))
CACHES = {
    "default": {
        "BACKEND": os.environ.get(
            "DJANGO_CACHE_BACKEND",
            "django.core.cache.backends.locmem.LocMemCache",
        ),
        "LOCATION": os.environ.get("DJANGO_CACHE_LOCATION", "ultracoachmatrix"),
        "TIMEOUT": DASHBOARD_CACHE_TIMEOUT,
    }
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5000",
    "http://localhost:5173",
    "http://localhost:8080",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8080",
    "http://10.0.2.2:3000",
    "http://10.0.2.2:5000",
    "http://10.0.2.2:5173",
    "http://10.0.2.2:8080",
]


CORS_ALLOW_ALL_ORIGINS = True

FIREBASE_CREDENTIALS_FILE = os.environ.get(
    "FIREBASE_CREDENTIALS_FILE",
    os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", ""),
)
FIREBASE_PROJECT_ID = os.environ.get("FIREBASE_PROJECT_ID", "")
PUSH_NOTIFICATIONS_ENABLED = os.environ.get("PUSH_NOTIFICATIONS_ENABLED", "true").lower() in {"1", "true", "yes"}

# Background jobs
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/1")
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_TIMEOUT = int(
    os.environ.get("CELERY_BROKER_CONNECTION_TIMEOUT", "2")
)
CELERY_TASK_PUBLISH_RETRY = False
CELERY_TASK_ALWAYS_EAGER = os.environ.get("CELERY_TASK_ALWAYS_EAGER", "false").lower() in {
    "1",
    "true",
    "yes",
}
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_WORKER_PREFETCH_MULTIPLIER = int(
    os.environ.get("CELERY_WORKER_PREFETCH_MULTIPLIER", "1")
)
CELERY_BEAT_SCHEDULE = {
    "recover-stale-background-jobs": {
        "task": "institute_admin.recover_stale_background_jobs",
        "schedule": float(os.environ.get("BACKGROUND_JOB_RECOVERY_INTERVAL", "300")),
    },
}

BACKGROUND_JOB_MAX_RETRIES = int(os.environ.get("BACKGROUND_JOB_MAX_RETRIES", "3"))
BACKGROUND_JOB_RETRY_DELAY = int(os.environ.get("BACKGROUND_JOB_RETRY_DELAY", "30"))
BACKGROUND_JOB_STALE_MINUTES = int(os.environ.get("BACKGROUND_JOB_STALE_MINUTES", "30"))
BACKGROUND_JOB_PENDING_REDISPATCH_MINUTES = int(
    os.environ.get("BACKGROUND_JOB_PENDING_REDISPATCH_MINUTES", "5")
)
BACKGROUND_JOB_SYNC_FEE_FALLBACK = os.environ.get(
    "BACKGROUND_JOB_SYNC_FEE_FALLBACK",
    "true",
).lower() in {"1", "true", "yes"}
BACKGROUND_JOB_SYNC_NOTICE_FALLBACK = os.environ.get(
    "BACKGROUND_JOB_SYNC_NOTICE_FALLBACK",
    "false",
).lower() in {"1", "true", "yes"}
